### ISSUE TITLE
Should the expiration value remain after second save?

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#1]
Consider this: 

``` php
// T = 0
$item = $pool->getItem('key');
$item->set('value');
$item->expiresAfter(3600);
$pool->save($item);

// T = 600
$item = $pool->getItem('key');
$item->set('foobar');
$pool->save($item);
```

For how long is the item still in cache? The way I see it there are three options:
- A) Until T=3600
- B) Until T=4200
- C) Forever since `$item->expiresAfter()` was never called. 

I believe that option A is preferable. 

This question has a lot of impact on performance. If C is the right way we do not have to read to the cache before doing a store. 

**EDIT** Correct answer is C

From @Nyholm: The correct answer was C according to the mailing list. We need to write a test for that.

**Comment by Nyholm** [comment]
This is fixed in latest releases and in test
