### ISSUE TITLE
Difference from Symfony Cache

### ISSUE THREAD

**Issue by Filoz** [php-cache/issues#104]
Hi, 
Is there a comparison between this library and Symfony Cache (http://symfony.com/blog/new-in-symfony-3-1-cache-component) ?
In which way are they different? 
Both are an implementation  of  PSR-6 Caching Interface...

Thank You!

**Comment by Nyholm** [comment]
Hey. 
There is no official comparison. We have some more features and support Symfony 2.8+. 
Example features are tagging, hierarchy, namespace and prefix. The symfony cache is working on tagging. 

Read more about it at php-cache.com

**Comment by prisis** [comment]
Going to close this one :)
