### ISSUE TITLE
Namespaced pool does not implement hierarchical interface

### ISSUE THREAD

**Issue by gsouf** [php-cache/issues#105]
Hi,

The namespaced cache pool constructor takes a hierarchical pool as argument, but it does not implement hierarchical interface itself.

Is it on the purpose? 

In my case it causes issue because I have a method that depends on hierarchilcal interface:

```php
    pubilc function someMethod(Cache\Hierarchy\HierarchicalPoolInterface $pool);
```

**Comment by gsouf** [comment]
@Nyholm Please, if you provide further details I would be glad to contribute

**Comment by Nyholm** [comment]
Hey. Sorry I missed this. 

Yes it is on purpose. We need an hieracal pool achieve proper name spacing. (It should be better documented)

Have a look at the prefix pool. It is a small section describing the differencies between namespace and prefix at the start page: http://www.php-cache.com/en/latest/

**Comment by gsouf** [comment]
Thank you @Nyholm my question was mostly about the fact that namespaced cache should implement itself the Hierarchical pool because it is fully compatible with it due to the inner cache being a hierarchical pool.

Concerning prefix pool, I'm not sure to understand the difference with namespaced cache, I will dig into the  sources to check, but if in the interim you can give further details, I will be able to update the documentation accordingly

**Comment by Nyholm** [comment]
> Thank you @Nyholm. However my question was mostly about the fact that namespaced cache should implement itself the Hierarchical pool because it is fully compatible with it due to the inner pool being a hierarchical pool, shouldn't it?

Sorry.. It does support hierarchal keys, so why not add the HierarchicalPoolInterface to it 👍 

------

The differences are: 
1) With the prefix, you could still have conflicts if one cache key includes the prefix. 

Ie: 
```php
// This
$prefixedPool = new PrefixedPool($pool, 'prefix_');
$prefixedPool->getItem('foo');

// Same as this:
$pool->getItem('prefix_foo');
```

2) When clearing the cache all cache items will be cleared, not only the prefixed ones.

It may be that the docs are unclear, I would be happy to get a better suggestion.

**Comment by gsouf** [comment]
Correct me if I'm wrong, but after looking at the sources it appears that the following happens:

**Prefixed pool** with prefix ``"myprefix"`` will transform the key ``"foo|bar"`` to ``'myprefixfoo|bar"`` and clearing the cache will delete everything even not prefixed keys.

**Namespaced pool** with namespace``"myns"`` will transform the key ``"foo|bar"`` to ``"|myns|foo|bar"`` and clearing the cache will delete only keys under that namespace ``"|myns"``.

**Comment by Nyholm** [comment]
Yes. Correct.

**Comment by gsouf** [comment]
@Nyholm I spot the same issue with Prefixed cache pool. 

The property is annoted to be a hierarchical pool: https://github.com/php-cache/prefixed-cache/blob/master/PrefixedCachePool.php#L25

But in the constructor the cache pool is set to be a simple CachePoolInterface. Should Prefixed cache depend on Hierarchical pool?  If so, that would introduce a BC break

**Comment by Nyholm** [comment]
> Should Prefixed cache depend on Hierarchical pool?

No. 

The property should be annotated with a normal CachePoolInterface
