### ISSUE TITLE
Psr6SessionHandler | Remove wrong InvalidArgumentException throw in doc 

### ISSUE THREAD

**Issue by prisis** [php-cache/issues#107]
https://github.com/php-cache/session-handler/blob/master/Psr6SessionHandler.php#L48

**Comment by Nyholm** [comment]
What exception should be thrown? The session handler does not have a dependency on cache/common. It is also built for ANY PSR 6 cache.

**Comment by prisis** [comment]
I said to remove the wrong exception info, we dont throw a exception in __construct function

**Comment by Nyholm** [comment]
Oh. You are correct. I understand now  :)
