### ISSUE TITLE
Allow  hierarchical cache to use natural keys (not sha1 encoded)

### ISSUE THREAD

**Issue by gsouf** [php-cache/issues#110]
Hi,

I would like to propose a solution to allow cache adapters that support any character as a key to use the natural key instead of the sha1 version of the key.

The reason behind this request is that sha1 keys are limitative for adapters like redis. Redis supports all characters as a key and is totally safe, in addition redis allows to search keys based on regexp and that's very helpful and much more flexible than hierarchical system in some circumstances.

That means that when using php-cache with redis (or similar adapters) we loose a lot of the ability of redis to work with keys in an efficient manner.

Do you think it would be a good addition in the library?

Thanks

**Comment by Nyholm** [comment]
Hey. 
I do understand your case. I do not think it is possible when you consider the edge cases. Previously we had issues with keep being to long which broke some storages. Also, all storages does not support all characters in the keys. 

I currently do not see this feature working its way into the lib... But I may be wrong, if there is a good solution I would be happy to merge it. 

I suggest you to extend the Redis adapter and make sure it override the `getHierarchyKey`.

**Comment by gsouf** [comment]
Hi @Nyholm 

I take note of your comment.

Of course I can use my one class extending php-cache, but if it can benefit the whole library that would be great, I think.

I was thinking of implementing this feature only for storages that support all characters (for instance redis that is ultra flexible on this point). This feature would be disabled by default and it would be enabled when constructing the storage instance; exemple: 

```php
   $pool = new RedisCachePool($redis, false) ; // false for disabling sha1 keys
```

**Comment by prisis** [comment]
im with @Nyholm if we start to add some extra features to redis, then we gone do it for all other adapters

Im closing this with wont fix
