### ISSUE TITLE
Prefix cache addapter is not PSR-16 compliant.

### ISSUE THREAD

**Issue by ndobromirov** [php-cache/issues#111]
See declaration...
```
class PrefixedCachePool implements CacheItemPoolInterface
```

The simple cache interface is completely missing. It is present on Memcache, as it extends the `AbstractCachePool` base utility. 
```
class MemcachedCachePool extends AbstractCachePool implements HierarchicalPoolInterface
```

**Comment by prisis** [comment]
Hey :), maybe you have some time to add a new PrefixedSimpleCache class?

**Comment by Nyholm** [comment]
:+1:

**Comment by ndobromirov** [comment]
Why not just extend the `AbstractCachePool` and make `PrefixedCachePool` work with both as all other cache adapters?

**Comment by prisis** [comment]
Because PrefixedCachePool is a wrapper for PSR-6 and not a adapter

**Comment by ndobromirov** [comment]
So let's have some progress on this :) https://github.com/php-cache/cache/pull/171
