### ISSUE TITLE
Namespaced cache pool does not work as expected.

### ISSUE THREAD

**Issue by guyradford** [php-cache/issues#119]
The Namespaced cache pool `save` and `saveDeferred` method do not add the namespace to the start of the cache key.

Why was it implemented this way? This means its not a proper decorator class.

**Comment by prisis** [comment]
Do you use the NamespacedCachePool::getItem to get namespaced item?

**Comment by guyradford** [comment]
When saving a new CacheItem, the key is not prefixed. Therefore it cant be retrieved with `getItem` which does prefix the cache key.

**Comment by prisis** [comment]
Can you show a bit of code?

**Comment by guyradford** [comment]
```
$arrayCache = new ArrayCachePool();
$namespacedCache = new NamespacedCachePool($arrayCache, 'PREFIX');
        
$item = (new CacheItem('test'))
    ->set('test string');

$namespacedCache->save($item);
        
echo "Expected:true\n";
var_dump($namespacedCache->hasItem('test'));

echo "\nExpected:false\n";
var_dump($arrayCache->hasItem('test'));
```

Output
```
Expected:true
bool(false)

Expected:false
bool(true)
```
This shows that the prefix is not being added when saving via the namespacedCachePool decorator.

**Comment by prisis** [comment]
You shouldnt create a new CacheItem, just use the getItem function https://github.com/php-fig/cache/blob/master/src/CacheItemPoolInterface.php#L19

The CacheItem only has a getKey function so we cant change the key, if the class is created. https://github.com/php-fig/cache/blob/master/src/CacheItemInterface.php#L35

Try this:
```php

$arrayCache = new ArrayCachePool();
$namespacedCache = new NamespacedCachePool($arrayCache, 'PREFIX');

$item = $namespacedCache->getItem('test');
$item->set('test string');

$namespacedCache->save($item);
        
echo "Expected:true\n";
var_dump($namespacedCache->hasItem('test'));

echo "\nExpected:false\n";
var_dump($arrayCache->hasItem('test'));
```

**Comment by guyradford** [comment]
This mean we now have to update a large amount of code.
To update the cache key, reflections could be used or create a new CacheItem object with the values from the first. This would allow cache key to be updated and provide a full decorator class.

I may try to make a PR if I get time.

Thank you

**Comment by prisis** [comment]
I'm sorry, psr-6 works like that... And in our doc's you can find the same example http://www.php-cache.com/en/latest/introduction/

**Comment by guyradford** [comment]
Oh, my misunderstanding... I had missed the fact the cache item should be
created by the pool.
