### ISSUE TITLE
Cache Util Package

### ISSUE THREAD

**Issue by ragboyjr** [php-cache/issues#121]
It would be nice if the php-cache ecosystem had a util package that implemented utility functions on top of the psr-6 and psr-16 interfaces.

An example function would be something like.

```php
<?php

namespace Cache\Util;

use Psr\SimpleCache\CacheInterface;

function remember(CacheInterface $cache, $key, $ttl, callable $fetch) {
    $res = $cache->get($key);
    if ($res) {
        return $res;
    }

    $res = $fetch();
    $cache->set($key, $value, $ttl);
    return $res;
}
```

Usage:

```php
$cache = new ArrayCache();
$res = Cache\Util\remember($cache, 'key', 3600, function() {
    // return some expensive query here.
});
```

I can't think of any other utility functions, but that is a very common pattern when accessing cache items and it seems like utility functions would fit well with the Cache packages.

**Comment by Nyholm** [comment]
Sure. Make a PR and I’ll be happy to create such package

**Comment by ragboyjr** [comment]
You got it!

**Comment by ragboyjr** [comment]
@Nyholm done.
