### ISSUE TITLE
filesystem-adapter does not work with PHPOffice / PhpSpreadsheet. (simple fix)

### ISSUE THREAD

**Issue by inet2800** [php-cache/issues#125]
The problem is the regex test on line 144 of FilesystemCachePool.php. The file name does not allow a dash, which PhpSpreadsheet uses for the key name.  While not very common, I do not see an issue with dashes in a file name.

orig code: preg_match('|^[a-zA-Z0-9_\.! ]+$|', $key))

fix code:   preg_match('|^[a-zA-Z0-9_\-\.! ]+$|', $key))

**Comment by prisis** [comment]
If you read the psr-6 dashes are not supported

Key - A string of at least one character that uniquely identifies a
cached item. Implementing libraries MUST support keys consisting of the
characters A-Z, a-z, 0-9, _, and . in any order in UTF-8 encoding and a
length of up to 64 characters. Implementing libraries MAY support additional
characters and encodings or longer lengths, but must support at least that
minimum. Libraries are responsible for their own escaping of key strings
as appropriate, but MUST be able to return the original unmodified key string.
The following characters are reserved for future extensions and MUST NOT be
supported by implementing libraries: {}()/\@:

**Comment by prisis** [comment]
Welcome :)
