### ISSUE TITLE
Add a new Component for PSR7 Http Cache + PSR15 Middleware

### ISSUE THREAD

**Issue by prisis** [php-cache/issues#126]
Utils that can be used
https://github.com/micheh/psr7-cache

Optional Features
- Send cache invalidation requests with minimal impact on performance.
- Cache tagging abstraction, uses BAN with Varnish and allows tagging support for other caching proxies in the future.
- Use the built-in support for Varnish 3, 4 and 5, NGINX, the Symfony reverse proxy from the http-kernel component or easily implement your own caching proxy client.
- Test your application against your Varnish or NGINX setup.
- https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/

**Comment by Nyholm** [comment]
Oh, that is great

**Comment by prisis** [comment]
First i need to finish my old tickets :D (the day needs more hours haha)
