### ISSUE TITLE
Class Memcached not autoloaded

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#140]
When I run

`bin/console cache:clear`

I get the following

```
Fatal error: Class 'Memcached' not found in .../vendor/cache/adapter-bundle/src/ProviderHelper/Memcached.php on line 19

Attempted to load class "Memcached" from the global namespace.  
  Did you forget a "use" statement? 
```

The file has in it

class Memcached extends \Memcached

I have memcached php extension installed and enabled in both php .ini files.

If I run `memcached -v` I get `memcached 1.5.12`

I had a similar problem recently #133 , but it seems to have come back when I changed php versions, and I can't resolve it in the same way.

**Comment by PaddyLock** [comment]
seems to work with php before like this

`php bin/console cache:clear`

**Comment by prisis** [comment]
Can you run php -m and post the output?

**Comment by PaddyLock** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imap
intl
json
ldap
libxml
mbstring
memcached
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug

**Comment by prisis** [comment]
Your sure that it is the same php bin that you using for your application?

**Comment by prisis** [comment]
Than you need to find the right php bin and add the memcache, I can't help you with this, sorry!
