### ISSUE TITLE
Possible tagging api issues

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#21]
From @andrerom:

Looking at this, I see there might be an issue here, depending on what the intention is here.

## Current API

Cache tagging in the FOSHttpCache and Drupal 8 sense, is tags that you typically don't know about when requesting the item, you only know it once the item, or it's corresponding entity in database is loaded.

Example would be a cache item representing entity with id 40 of type=article with author id=10, then key might be 'entity:40' and tags would be `['type' => 'article', 'author', 10]`, allowing you to invalidate/expire all items tagged with either type article, or author 10 later on when something changes to them, including item 'entity:40'.

Further examples can be found in Drupal 8 API doc: https://api.drupal.org/api/drupal/core%21core.api.php/group/cache/8

## Implementation of such approach

So afaik no cache backends supports tagging natively, I thought for a while Redis did, but can't find anything on that atm, pity.

For the items we can simply store tags inside same cache, ala `['value' => (...), 'tags' => [..]]`.

For invalidation we'll also need the reverse relation somewhat given we can't walk/query the cache.

Most likely the most performant and secure approach is to actually insert all tags to item key maps into a database\*, this is what is done in D8 and currently also in progress in FOSHttpCache, at least I can't seem to avoid hitting the following issues when trying to look for a way to avoid that:

A. If we opt of storing tags separately where key is tag name and value is list of items tagged with it, then: 
- Given most cache backends tend to drop items at any point if it starts to fill up some of it's cache blocks => if the tags to items map is wiped, effectively we don't know which items should be invalidated anymore.
- Storages like memcache does not have a notion of arrays, can use strings and append, but question is when you'll hit limits on that 
- When clearing by tag we would need to be able to do a blocking read and replace/delete to be somewhat atomic on the tag itself
 - Once you have the item keys, a multi set / delete can wipe out or expire all items

B. If we opt for just handling tags using expiry *(key is tag and value is expiry time)*, then:
- *same as first cache tag being wiped issue above*
- we now need to do several reads, once we have a cache item, if it has tags we will need to do a multi get to get expiry time stamp for all relevant tags => As I'm personally keen on avoiding several round trips to cache server, this is thus most likely not an option

In database on the other side, it is only read on invalidation, and only written to on save calls when item has tags.

**Comment by Nyholm** [comment]
So if I understand this correctly there is two options for using tags: 

Current A)
```php
$item = $pool->getItem('key', ['tag']); // Fetches item 1
$pool->save($item);
$pool->getItem('key'); // Fetches item 2
```

D8 style B)
```php
$item = $pool->getItem('key');
$item->setTags(['tag']);
$pool->save($item);
```

Solution **B** means that you can fetch an object without knowing all of its tags. It comes with a side effect of that is that you can not use tags as namespaces. 

---------

> Example would be a cache item representing entity with id 40 of type=article with author id=10, then key might be 'entity:40' and tags would be ['type' => 'article', 'author', 10], allowing you to invalidate/expire all items tagged with either type article, or author 10 later on when something changes to them, including item 'entity:40'.

When I read this example the fourth time I understood something important. It is a difference between tags and namespaces. What we have implemented is namespaces.

I want to do something like this. 
```php
$item = $pool->getItem('40', ['article']);
$item->set($post);
$item->setTags(['author_10', 'category_php']);
$pool->save($item);

// Someone requests that post
$item = $pool->getItem('40', ['article']);

// I want to clear all post by author
$pool->clearTags(['author_10']);

// I want to clear all articles
$pool->clear(['article']);
```

The valuable difference here is that I do not have to know all the tags (eg. the author and category) of the article to fetch it from the cache. But I do need to know the namespace (eg. article). 

So the question is, do we want to support both **tags** and **namespaces**?

**Comment by andrerom** [comment]
For me clear('article') is hierarchical cache, at least how it works in stash (PHP). And if you have tags you IMO don't really need it, cause you can have a "type-article" tag that you can do expiry/invalidation on. And unlike hierarchical cache it won't result in several cache lookups to get the every single cache item as is the case in Stash.

Namespace for me is internal and prefixed on keys and tags to be able to have several cache pools on same cache backend, like is the case in both the new sf cache component and stash.

**Comment by Nyholm** [comment]
Clear(['article']) could be using hierarchy and sure you could solve most problems (if not every) with tags instead of hierarchy. 

If the namespace is just a prefix that gets prefixed to the key then you can't clear all items in a namespace. I.e. 

Public function getItem($key) {
  return $this->cache->get('ns'.$key);
}

**Comment by andrerom** [comment]
> If the namespace is just a prefix that gets prefixed to the key then you can't clear all items in a namespace. I.e.

add a namespace tag and clear by it ;)

**Comment by Nyholm** [comment]
I will argue that you would need both namespaces and tags. Both could be used when you clear them but it is when you fetch objects they make a difference. Namespaces do not share keys and you have to know the namespace when you require an item

```php
// Namespace
$item1 = $pool->getItem('foo', ['ns1]);  // Item 1
$item2 = $pool->getItem('foo', ['ns2]);  // Item 2
```

Tags are basically just something that you can clear the cache by. You do not have to consider them when you require an item.

**Comment by andrerom** [comment]
I don't fully see the point of that one, way would you want namespace implicit all over your code?
In our case we have a [thin decorator](https://github.com/ezsystems/ezpublish-kernel/blob/master/eZ/Publish/Core/Persistence/Cache/CacheServiceDecorator.php) to inject in places we want to prefix with own vendor name to avoid conflicts.

**Comment by Nyholm** [comment]
> In our case we have a thin decorator to inject in places we want to prefix with own vendor name to avoid conflicts.

But how can you clear all items in that namespace?

**Comment by Nyholm** [comment]
Sorry... reading the code..

**Comment by andrerom** [comment]
In current approach `cache->clear()`, as it is hierarchical.
However reason why I'm thinking of handling this with tags underneath instead is because of the read overhead of hierarchical caching, which slows down perf on setups where cache server has latency. Which again is why I think multi get and being able to do as few round trips as possible is crucial for great perf.

**Comment by Nyholm** [comment]
You are absolutely correct with the performance bottle necks. 
Hierarchy keys has a lookup time complexity of O(n+1) = O(n) where n is the level in the hierarchy. Tagging has lookup time complexity if O(n+1) = O(n) where n us the number of tags. 

-----

Im slowly getting your points. =) I like the idea of a decorator that provide for namespace support by using hierarchical keys. Good!

So we "just" need to change the API and implementation of the tagging to make it look more like: 
```php
$item = $pool->getItem('article_40');
$item->set($post);
$item->setTags(['author_10', 'category_php']);
$pool->save($item);

// Someone requests that post
$item = $pool->getItem('article_40');

// I want to clear all post by author
$pool->clearTags(['author_10']);

```

**Comment by andrerom** [comment]
> Tagging has lookup time complexity if O(n+1) = O(n) where n us the number of tags.

Why would you need to lookup tags? As description says, you'll only need to lookup tags on invalidation if they are persisted. You'll also need to care for them on save, but not on `getItem(s)`.

So imho for GetItem:
- Hierarchy: O(n+1)
- Tags: O(1)

And with multi get, getItems:
- Hierarchy: O((i)*(n+1))
- Tags: O((1)*(1)) = O(1)

**Comment by Nyholm** [comment]
I misspoke. You are correct. I was thinking of the current implementation of tags. 

I am :+1: for updating the API of tags.

**Comment by Nyholm** [comment]
Fixed by https://github.com/php-cache/cache/pull/32
