### ISSUE TITLE
Interface to typehint against 

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#22]
When I require a cache pool that has taggs in my app I would like to type hint against something that allow me to use tag but also include the `CacheItemPoolInterface::save`. 

I can't use `TaggablePoolInterface` since it does not have a save function. Is it a good solution to create an interface that extends both `TaggablePoolInterface` and `CacheItemPoolInterface` and make sure adapters implement the new interface?

**Comment by aequasi** [comment]
Discussion: Should `TaggablePoolInterface` extend `CacheItemPoolInterface`

**Comment by Nyholm** [comment]
> Discussion: Should TaggablePoolInterface extend CacheItemPoolInterface

Say that we have the following:

```php
interface Animal {
  public function getName();
}
interface CanSpeak 
  public function speak($word);
}
class Parrot implements Animal, CanSpeak {
  // ...
}
```

How do I properly type hit the following: 
```php
class AnyService {
  private $animal;
  public function __construct(Animal $animal) { // <-- This line
    $this->animal = $animal;
  }
  public function speakName() {
    $this->animal->speak($this->animal->getName());
  }
}

I can only come up with a solution where `Parrot` implements one interface like `AnimalThatCanSpeak`. But that does not really makes sens if we also have interfaces for `CanWalk`, `CanFly`, `CanDrink` etc. Or does it?

**Comment by magnusnordlander** [comment]
The problem is that TaggablePoolInterface isn't usable by itself. I think the cleanest solution would be to declare a save method on TaggablePoolInterface.

**Comment by Nyholm** [comment]
Thank you @magnusnordlander 

It turns out that that is the only solution since `TaggablePoolInterface` cannot extend `CacheItemPoolInterface`.
