### ISSUE TITLE
Update tagging and adapter common versions

### ISSUE THREAD

**Issue by Nyholm** [php-cache/issues#23]
We need to update all our adapters to use `cache/adapter-common: ^0.2` and `cache/taggable-cache:^0.3`. These updates will not be backwards compatible. 

* [x] Apc
* [ ] Apcu
* [ ] Array
* [x] Doctrine
* [x] Filesystem
* [ ] Memcache
* [x] Memcaced
* [ ] MongoDB
* [ ] Predis
* [x] Redis
* [x] Void
* [ ] Chain
* [x] CacheBundle
* [x] Hierarchical cache

**Comment by prisis** [comment]
Void is ready too :)

**Comment by Nyholm** [comment]
Thank you

**Comment by Nyholm** [comment]
This is fixed by https://github.com/php-cache/cache/pull/32
