### ISSUE TITLE
Create cache/cache meta project

### ISSUE THREAD

**Issue by maidmaid** [php-cache/issues#25]
Hi !

Why not create a meta project that requires all adapaters? This project will contain only a composer.json that would look like this:

```json
{
    "name": "cache/cache",
    "require": {
        "cache/apc-adapter": "^0.1",
        "cache/apcu-adapter": "^0.1",
        "cache/array-adapter": "^0.1",
        "..."
    }
}
```

Like that, lazy developers (as me) just have to do ``composer require cache/cache``.

**Comment by prisis** [comment]
Im for a easy maintenance,  why you dont use something like git subsplit. So you have only one repo for all caches?

**Comment by aequasi** [comment]
https://github.com/php-cache/cache

We are working on this right now.

**Comment by maidmaid** [comment]
``cache/cache`` is the main working repository and ``cache/*-adapter`` and others are subtree splits?

**Comment by Nyholm** [comment]
Exactly.. The cache/*-adapter will become readonly

**Comment by maidmaid** [comment]
:+1:

**Comment by prisis** [comment]
@maidmaid if you like, you can join us on gitter
