### ISSUE TITLE
Allow using DSN for connections

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#26]
Allow using DSN for connections on drivers like Redis and Mongo

redis://localhost:6379
mongodb://user:pass@localhost:27107/

**Comment by Nyholm** [comment]
Does this belong to the adapter bundle?

**Comment by aequasi** [comment]
Yeah

Aaron Scherer




On Mon, Jan 25, 2016 at 11:49 PM -0800, "Tobias Nyholm" <notifications@github.com> wrote:












Does this belong to the adapter bundle?
