### ISSUE TITLE
Notice: Undefined index: use_tagging

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#30]
I get the following notice thrown in

Cache\CacheBundle\Factory\DoctrineBridgeFactory

But I’m not sure where to put this in the config to fix it.

**Comment by Nyholm** [comment]
Does this PR fix your issue: https://github.com/php-cache/cache-bundle/pull/50

**Comment by PaddyLock** [comment]
Hi, yes it should do i think. How do I get the change?

**Comment by aequasi** [comment]
Tagged a new version of the bundle, you should be able to get it from there

**Comment by PaddyLock** [comment]
Great, thanks, that has fixed the issue.
