### ISSUE TITLE
Invalid cache key for doctrine

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#31]
I get the following error when using doctrine caching and I’m not sure how to change the name of the cache key.

Invalid key: ”MyNameSpace\CoreBundle\Entity\User$CLASSMETADATA”. The key contains one or more characters reserved for future extension: {}()/\@:

**Comment by Nyholm** [comment]
Will this solve the issue: https://github.com/php-cache/doctrine-bridge/pull/10
?

**Comment by PaddyLock** [comment]
Yes, that should do it, thanks!

**Comment by PaddyLock** [comment]
Thanks, that has fixed the issue.
