### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#4]
We need a new logo!

Suggestions are open, and welcome!

**Comment by Nyholm** [comment]
![logo](https://cloud.githubusercontent.com/assets/1275206/12530580/1fac0e76-c1e3-11e5-9b1c-44a210210ee1.png)

**Comment by Nyholm** [comment]
![logo2](https://cloud.githubusercontent.com/assets/1275206/12530595/8e17cf62-c1e3-11e5-8e0a-f704a3432385.png)

**Comment by michaelcullum** [comment]
Looks a little... PHP 4. Using the old colour scheme and old logo doesn't help that either.

**Comment by Nyholm** [comment]
Yeah, it looks kind of old age. 
But the color scheme? I used the colors from here: http://php.net/download-logos.php

**Comment by michaelcullum** [comment]
Oh yeah, that page is kinda outdated. I'll fix that.

You can get the new logos etc. from http://www.cowburn.info/2015/06/18/php7-logo/

**Comment by Nyholm** [comment]
Are all these colors a part of the new color scheme?

**Comment by Nyholm** [comment]
![logo](https://cloud.githubusercontent.com/assets/1275206/12530907/de7a5f56-c1ed-11e5-8ef3-446608694756.jpg)

**Comment by Nyholm** [comment]
![logo](https://cloud.githubusercontent.com/assets/1275206/12530912/e7e67afc-c1ed-11e5-8ddf-7d9d2dd1131e.jpg)

**Comment by Nyholm** [comment]
![logo](https://cloud.githubusercontent.com/assets/1275206/12530922/0cb8c902-c1ee-11e5-8b64-bca720197d47.jpg)

Updated with new colors.

**Comment by michaelcullum** [comment]
:+1: I like it

**Comment by Nyholm** [comment]
thank you

**Comment by mablae** [comment]
![image](https://cloud.githubusercontent.com/assets/389360/12531093/01797c8a-c1f3-11e5-842f-167b62dd6044.png)


Maybe some isomorphic?

**Comment by Nyholm** [comment]
@mablae  Cool. I really like that! :+1:  Maybe add the new color scheme to it? Can you write PHP cache on it as well?

**Comment by mablae** [comment]
Yeah, that was the idea...:-)

**Comment by mablae** [comment]
![image](https://cloud.githubusercontent.com/assets/389360/12531242/a7aa9c5e-c1f5-11e5-9e95-4fe6ee7fd51f.png)

Now trying top add text...

**Comment by Nyholm** [comment]
You are awesome!

**Comment by mablae** [comment]
![image](https://cloud.githubusercontent.com/assets/389360/12531670/de7ad72a-c200-11e5-89b2-50a5bee1c01f.png)

**Comment by Nyholm** [comment]
Cool. What do you think @aequasi ?

**Comment by mablae** [comment]
Photoshop 3D is pure pain :smile:

**Comment by aequasi** [comment]
I like it :)

**Comment by Nyholm** [comment]
Cool. Let's go with this then. I just send a tweet about it to see if we get any feedback. 

The logo need to be in 3 formats. 
1) Just a PNG to use on github, slack, www.php-cache.com etc. 
2) A white version to use in the symfony 2.8+ toolbar. It must be a svg file with height of **24px**
3) A black version to use in the symfony 2.7 toolbar. It must be a svg file with heigh of **28px** 

Would you mind pushing the source and these 3 versions to https://github.com/php-cache/documentation ?

**Comment by Nyholm** [comment]
Sorry, not black and white. I mean dark and light grey. Se examples: 
![screen shot 2016-01-23 at 18 53 47](https://cloud.githubusercontent.com/assets/1275206/12531738/aa75b092-c202-11e5-82e8-2672b57379f5.png)
![screen shot 2016-01-23 at 18 53 32](https://cloud.githubusercontent.com/assets/1275206/12531737/aa73741c-c202-11e5-936f-973f9d449332.png)

**Comment by mablae** [comment]
Yeah, sure. Cool. Color is irrelevant on SVG it's just a Path. 
I need to find a way how to strip the details out and make it black/transparent only.

Also small 16x16 , 32x32, 64x64 versions for favicons would be nice :+1: 

I will contribute all the sources, sure..

**Comment by Nyholm** [comment]
:+1:

**Comment by michaelcullum** [comment]
Personally I kinda preferred the penultimate one but with php on it, the shadows in the last one are slightly inconsistent and the angle makes it look a lot larger.

**Comment by mablae** [comment]
This is current state: 
![image](https://cloud.githubusercontent.com/assets/389360/12536277/d2d0b430-c2a0-11e5-97b3-9c5ae50f61ca.png)

Any recommendations about color and style of the php logo appreciated!

**Comment by michaelcullum** [comment]
I think it looked good with the original set of colours (which are also the official colour scheme) and then the same black/dark grey that is in the logo pack linked to above. The best one yet is https://github.com/php-cache/issues/issues/4#issuecomment-174197614 I think, it just needs the logo and it would have been perfect.

**Comment by Nyholm** [comment]
Here is a PR with the logos: https://github.com/php-cache/documentation/pull/11
Lets continue the discussion of this suggestion there.
