### ISSUE TITLE
Fix integration-tests requirement

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#40]
Issue: Right now, when we run that script, SessionHandler and Bridge both have the `integration-tests` requirement, when they don't need it

Also, we could do this:

Update all the libraries so they just require `*` version or something, and then during the travis build, update them.

**Comment by Nyholm** [comment]
Why not make an exception for SessionHandler and Bridge?

**Comment by aequasi** [comment]
Yeah, we could
