### ISSUE TITLE
Symfony, annotation service definition

### ISSUE THREAD

**Issue by Tetragramat** [php-cache/issues#45]
> Fatal Error: Argument 3 passed to Cache\CacheBundle\Factory\DoctrineBridgeFactory::get() must be of the type array, string given

Defined at https://github.com/php-cache/cache-bundle/blob/master/src/DependencyInjection/CacheExtension.php#L127
making that array fixes the issue

Same problem may be with serializer. Not tested.
https://github.com/php-cache/cache-bundle/blob/master/src/DependencyInjection/CacheExtension.php#L136

**Comment by Nyholm** [comment]
Awesome, I think I know what you mean. Do you mind sending a PR?
