### ISSUE TITLE
Expiration

### ISSUE THREAD

**Issue by DrSchimke** [php-cache/issues#46]
I noticed a strange behavior. When I use `null` as argument for `expiresAfter`, everything is fine. (I use Redis, so the non-expiring SET operation is used.)

```php
$item = $pool->getItem('some key');
$item->set('some value');
$item->expiresAfter(null);
$pool->save($item); // works fine: "SET" "[some key][1]" ...
```
But when is use `0` as argument for `expiresAfter`, the `NULL` value is cached.
```php
$item = $pool->getItem('some key');
$item->set('some value');
$item->expiresAfter(0);
$pool->save($item); // strange: "SET" "[some key][1]" "s:2:\"N;\";"
```

I think, the problem is, that `$item->setExpiresAfter(0)` immediately makes the `$item->isHit()` return `false`. This is ok, but the _no-longer-hit_ `$item` is saved anyway. **Maybe `$pool->save($item)` should fail, if `false === $item->isHit()`?**

**Comment by Nyholm** [comment]
Thank you for reporting this. I saw this error the other day when I was working a new API for tagging. 
It is fixed in that PR. https://github.com/php-cache/cache/pull/32/files#diff-80db5ecc7734c9b1bbcf01f2fa676db4R72

**Comment by Nyholm** [comment]
Fixed by https://github.com/php-cache/cache/pull/32
