### ISSUE TITLE
memcached perf issues ?

### ISSUE THREAD

**Issue by morgangiraud** [php-cache/issues#51]
Hello everyone,

First, thanks for your work on those different bundles!

I'm currently monitoring my app with newrelic and i can see a 180 ms latency (this an average but it never goes down even after a week) only attributed to memcached which is unlikely to be normal.
Are you aware of any performance issue concerning the memcached bundle ?

**Comment by Nyholm** [comment]
Hey. 
Thank you for appreciating the work. 
Where is the latency? In the connection with Memcached? 

We have written the adapters in a way so we reduce the roundtrips to the cache implementation. This will make the cache adapter more preferment. But if you talking about the latency from PHP to connecting to the Memcached server that is out of the scope of any PHP application. 

Say that you have your Memcached server in New York and your application in Stockholm. That would (naturally) be high latency. You would also get high latency if your server is slow or have a hard time setting up the connection.

**Comment by morgangiraud** [comment]
For now, i can see the latency from the PHP viewpoint.

The 2 instances (PHP instance and memcached) are exactly in the same area in AWS (same region, same zone) 
It usually means that there should not be any latency between those physical machines.

Do you know any tool to check memcached latency from the command line ?

**Comment by morgangiraud** [comment]
More on the situation:
I've just deployed a new version of my app in production and this is what happened:
<img width="946" alt="screen shot 2016-04-14 at 11 59 05" src="https://cloud.githubusercontent.com/assets/1278248/14524673/d0e7309e-0239-11e6-91b8-85bf9b684db9.png">
<img width="718" alt="screen shot 2016-04-14 at 12 07 05" src="https://cloud.githubusercontent.com/assets/1278248/14524676/d25d602e-0239-11e6-999b-a552c1e6147a.png">

So i rollback to previous version and everything was back to normal:
<img width="339" alt="screen shot 2016-04-14 at 11 59 35" src="https://cloud.githubusercontent.com/assets/1278248/14524688/dd7323d6-0239-11e6-9c4b-ea637eaf68aa.png">

Note that i was on the branch **fixtagging** which might be a bad idea after all.
I can't give much more information so far, hope it will allows you to improve on the subject.

**Comment by Nyholm** [comment]
Hm, Thank you. I'll investigate in this. 

@aequasi Do you know why this is happening?

**Comment by dkvk** [comment]
Do you have any traces from the transactions being made?

Mvh
Daniel
Den 14 apr. 2016 12:16 skrev "Tobias Nyholm" <notifications@github.com>:

**Comment by morgangiraud** [comment]
Sadly, i don't have anything.
It was slow and made the CPU utilisation increase quite fast but it was still working so no error trace nor slow trace (calls were still under 30s which is my config limit for slow tracing) and i revert the changes before hitting an overload.

**Comment by aequasi** [comment]
Only thing i could think of is that the keys are getting cleared, or the keys are changing per deploy? Im not sure what would cause this otherwise.

**Comment by morgangiraud** [comment]
@aequasi On our side, the keys are not changing per deploy, but maybe something change them due to  the different versions upgrade ?

**Comment by Nyholm** [comment]
I've looked at this issue time to time during the last year without being any wiser. Do you still experience this or have you created a workaround?

**Comment by Nyholm** [comment]
Thank you. Im closing this issue.
