### ISSUE TITLE
phpdbg is causing segfaults

### ISSUE THREAD

**Issue by Nyholm** [php-cache/issues#54]
When running tests on PHP7 we get segfaults. See void adapter: https://travis-ci.org/Nyholm/cache-1/builds/134103829

When not using the phpdbg everything passes. (See [change](https://github.com/Nyholm/cache-1/commit/eea6a5690c59348bff5ff836a7e60a178eb5537f)) https://travis-ci.org/Nyholm/cache-1/builds/134104452

Question: Why do we need `phpdbg`? Should we remove it?

**Comment by aequasi** [comment]
IIRC phpdbg was suggested to make tests run faster? I'm down to try without it though
