### ISSUE TITLE
Direct access to redis instance while using redis adapter.

### ISSUE THREAD

**Issue by akankov** [php-cache/issues#55]
Hey guys. 
I really want to have direct access to redis instance while using redis adapter.

Is it possible to make?

**Comment by prisis** [comment]
Hey :), you can extend the RedisCachePool class and add a
~~~php
public function getRedis() {
    return $this->cache;
}
~~~

**Comment by akankov** [comment]
I thought about it.

But cache is a **private** variable

**Comment by prisis** [comment]
oh didnt see it... can you make a pr and change it to protected?

**Comment by Nyholm** [comment]
@akankov Did https://github.com/php-cache/cache/issues/70 solve the issue for you?

**Comment by Nyholm** [comment]
Im closing this issue. Feel free to repen it again if the patch did not help you
