### ISSUE TITLE
Allow "namespacing" with Memcache Adapter (Symfony 3)

### ISSUE THREAD

**Issue by angelsk** [php-cache/issues#59]
Allow `MemcachedFactory` to construct `Memcached` with an (optional) persistent ID for namespacing between environments.

"cache/memcached-adapter": "^0.3.1",
"cache/adapter-bundle": "^0.3.3"

````
cache_adapter:
    providers:
        memcached:
            factory:    'cache.factory.memcached'
            options:
                host:   "%memcached.host%"
                port:   "%memcached.port%"
                persistant_id: "%memcached. persistant_id%"
````

**Comment by angelsk** [comment]
NOTE: This bug is related: https://github.com/php-cache/issues/issues/60

**Comment by Nyholm** [comment]
Fixed in https://github.com/php-cache/adapter-bundle/pull/38
