### ISSUE TITLE
[bug] AdapterBundle\MemcachedFactory doesn't use Cache\AdapterBundle\ProviderHelper\Memcached

### ISSUE THREAD

**Issue by angelsk** [php-cache/issues#60]
When the `Factory` creates the `Memcached` instance and calls `addServer` - it's going to add the same server multiple times - this seems to have been fixed in the `ProviderHelper` - but that class is not used.

**Comment by Nyholm** [comment]
Fixed in https://github.com/php-cache/adapter-bundle/pull/38
