### ISSUE TITLE
Namespaced cache not implemented support for Symfony

### ISSUE THREAD

**Issue by Tetragramat** [php-cache/issues#61]
It take me hours to find out there is NamespacedCachePool, but there is no support for Symfony.
I'm not able to create cache with namespace support, just by using configuration.
Or did I miss something?
There is missing documentation and implementation of NamespacedCachePool for Symfony.

**Comment by Tetragramat** [comment]
If it is really missing, can you provide me with an example for configuration (where in config.yml should be NamespacedCachePool options configured, etc..?), so I can try make a pull request?
@Nyholm @aequasi ?

**Comment by Nyholm** [comment]
Hm, maybe you are correct. I'll dig into this more next week. Expect some updates then

**Comment by Nyholm** [comment]
I've tagged AdapterBundle 0.3.5 with this fix.
