### ISSUE TITLE
Create Factories for Doctrine Cache

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#7]
We need **Doctrine** factories for: 

* [ ] Apc
* [ ] Apcu
* [ ] Array
* [x] Couchbase
* [ ] File
* [x] Filesystem
* [x] Memcache
* [x] Memcached
* [x] MongoDb
* [ ] PhpFile
* [x] Predis
* [x] Redis
* [x] Riak
* [x] SQLite3
* [ ] Void
* [x] WinCache
* [x] Xcache
* [x] ZendData

We do not have to do them all. Just do some popular and the once we do not have any adapters for.

**Comment by Nyholm** [comment]
That would be enough.
