### ISSUE TITLE
Better docs for new users

### ISSUE THREAD

**Issue by Nyholm** [php-cache/issues#70]
By @alexryderwhytewaters:

I just came here to suggest that you allow cache path to be changed via the constructor, but it looks like that has already been done. However the lastest composer package doesn't include that change yet. 

While I am at it, I will just mention a couple of other things (think of them as feedback, not good, not bad, just feedback from a first time user)

Your site has an example of how to do tagging and more complex stuff, but the only place I could find a simple example how how to create a pool is in github of the actual adapters themselves (maybe i missed something, but it wasn't easy to find). It would be nice if you can just add a 5 line example to the main site, showing accessing of a pool eg. and getting and item then saving it. 

Next issue i ran into is, i am caching webpages based on url, so the first thing i did is
$cachePool->getItem($_SERVER['REQUEST_URI']);

which failed, because you can't include certain characters for future features. So I am now using it like this
$cachePool->getItem(md5($_SERVER['REQUEST_URI']));

To me, the cache key, should not have reserved characters, maybe a separate parameter to provide extra features, but that's up to you, just feedback.

Next I went to add a tag, same thing limited to what i can use as characters, : not allowed
$item->set($html)->addTag("operator:{$operator->operator_rn}");

So now I am using underscore, to me it would seem more logical to allow any char and just encode the data, eg url_encode
$item->set($html)->addTag("operator_{$operator->operator_rn}");

Both issues, I struck are easy to work around, I only mentioned them as they were first impressions,
and I will have forgotten about them in a few weeks time

Your cache package seems to be the only filesystem one that handles tagging that i have found so far, so thank you for providing that.

**Comment by Nyholm** [comment]
Thank you for your thoughts. You are correct. We do assume that everybody knows PSR-6 which is of course false. I will add a page in the documentation about the issues you found. Because you are not alone

I have tagged 0.3.1 on the filesystem adapters.

**Comment by aequasi** [comment]
I'll quickly comment on the "key issue", regarding reserved characters.

For us to follow the PSR-6 spec @alexryderwhytewaters, we have to [restrict several characters](http://www.php-fig.org/psr/psr-6/#definitions) (see: Key), `{}()/\@:`, to be compliant with PSR-6.

Thanks for your input on the documentation, though, it needs some additions.

**Comment by alexryderwhytewaters** [comment]
I was completely not aware of PSR-6, now i have had a look at that, things make a lot more sense.

**Comment by Nyholm** [comment]
I really appreciate this feedback. 
I've created a new page in the documentation. See https://github.com/php-cache/documentation/issues/26

Would this have been helpful for you?
