### ISSUE TITLE
[Flysystem] File already exists at path

### ISSUE THREAD

**Issue by rvanlaak** [php-cache/issues#76]
We replaced the simple caching layer we had be fore with a CachePoolChain (APCu > Filesystem). Every now and then we get a `League\\Flysystem\\FileExistsException` with the following message:

> Exception thrown when executing \"save\":
> File already exists at path: cache/prod_key

I'm not sure why this happens, our code first checks if an entry exists and next to that always uses `pool->getItem` and doesn't construct cache items itself. In other words, basically this cache collission (?) should never happen right?

Shouldn't the filesystem adapter always catch the `FileExistsException` and handle that itself?

**Comment by rvanlaak** [comment]
ping @Nyholm, any idea in what scenarios this exception could occur?

**Comment by Nyholm** [comment]
Interesting. Is it possible that there is race condition? Is the filesystem local or remote?

I can't reproduce this locally, but I've made a PR that **may** solve the issue. Can you test it? 
https://github.com/php-cache/cache/pull/94

**Comment by rvanlaak** [comment]
The filesystem is local, Flysystem actually locates it in `/app/cache/dev/cache_folder/cache`. The weird part that with over 95% of the write actions the file would already exist but everything is okay. Next to that it is a bit hard to reproduce this on our `dev` environment, any ideas for that?

**Comment by Nyholm** [comment]
Do you only get these errors in production?

> The weird part that with over 95% of the write actions the file would already exist but everything is okay.

As you can see here we check if the file exists and then remove it if so. 
https://github.com/php-cache/cache/blob/0.3/src/Adapter/Filesystem/FilesystemCachePool.php#L95-L109

The PR I submitted makes sure we do `update` instead of `delete` and `write`.

**Comment by rvanlaak** [comment]
I actually just did an update of our application, and while the cache was re-building we got quite some of these errors. Could in any way this be anything performance related?

**Comment by Nyholm** [comment]
Could it be a possible race condition?

We do check if the file exists (if so delete) and the we write to the file.

> Could in any way this be anything performance related?

Im not sure. What did you have in mind?


Have you tried my patch?
https://github.com/php-cache/cache/pull/94

**Comment by rvanlaak** [comment]
On production I rather not deploy your patched version ;) and on `dev` I actually never had the exception so far. 

We did get four error reports when the process that fills the cache was running during the update process. That process results in a high load, so it might could have something to do with that? I'm not sure either, but there might even be two processes (read: http requests) that fill the cache because in the meanwhile another user started using the application.

**Comment by Nyholm** [comment]
> We did get four error reports when the process that fills the cache was running during the update process. That process results in a high load, so it might could have something to do with that? I'm not sure either, but there might even be two processes (read: http requests) that fill the cache because in the meanwhile another user started using the application.

Okey. So let's assume there is race condition. 

Can you review php-cache/cache#94? I think it will solve your issue. If you like the code I'll merge it in to master and create a new release for you.

**Comment by rvanlaak** [comment]
Yes the code looks great, especially the try/catch that will "solve" this exception I hope. As long as it passes all test cases I don't see any reason why not to merge and release it.

**Comment by rvanlaak** [comment]
This morning we had another type of exception on production. It might be related?

> "class": "League\\Flysystem\\FileNotFoundException",
> "message": "File not found at path: cache/prod_user_online_1731",
> "code": 0,
>    "file": "/application/vendor/league/flysystem/src/Filesystem.php:385",
>    "trace": [
>    "/application/vendor/league/flysystem/src/Filesystem.php:178",
>    "/application/vendor/cache/filesystem-adapter/FilesystemCachePool.php:72",
>    "/application/vendor/cache/adapter-common/AbstractCachePool.php:93",
>    "/application/vendor/cache/adapter-common/CacheItem.php:195",
>    "/application/vendor/cache/adapter-common/CacheItem.php:107",
>    "/application/vendor/cache/adapter-common/AbstractCachePool.php:121",
>    "/application/vendor/cache/chain-adapter/CachePoolChain.php:144",

**Comment by Nyholm** [comment]
yeah, maybe. I've updated the patc

**Comment by rvanlaak** [comment]
Working on the upgrade now. Had another bug on our ttl calculation, so will inform you tomorrow if the number of cache exception error reports has dropped.

**Comment by rvanlaak** [comment]
Updated yesterday evening, so far no error reports anymore 👍 Will give another status update later this week.

**Comment by Nyholm** [comment]
That is great. Awesome!

**Comment by rvanlaak** [comment]
Exceptions are fixed now, but we have another severe bug with the TTL now, see https://github.com/php-cache/issues/issues/80 .
