### ISSUE TITLE
Prefix on cache services in Symfony bundle (annotation, serializer, etc.)

### ISSUE THREAD

**Issue by iainmckay** [php-cache/issues#78]
The session service accepts a prefix. The others (annotation, serializer, validation, router) dont. Is there a technical reason for this?

We're running in to conflicts when we have multiple instances of our app running with slightly different configurations, they both use the same cache keys but different contents.

If there's no technical reason we will submit a PR.

Thanks

**Comment by Nyholm** [comment]
No, there is not any reason for it as far as I know. They should all be able to accept a prefix.

I would be happy to see a PR. If you like to you may use this package I created last week: https://packagist.org/packages/cache/prefixed-cache
