### ISSUE TITLE
Planned Adapters

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#8]
These are the adapters that we should support. 
- [x] Apc https://github.com/php-cache/apc-adapter
- [x] Apcu https://github.com/php-cache/apcu-adapter
- [x] Array https://github.com/php-cache/array-adapter
- [x] Chain https://github.com/php-cache/chain-adapter
- [ ] Couchbase ?
- [x] Doctrine Cache
- [ ] File
- [x] Filesystem (flysystem) https://github.com/php-cache/filesystem-adapter
- [x] Memcache https://github.com/php-cache/memcache-adapter
- [x] Memcached https://github.com/php-cache/memcached-adapter
- [ ] Mongodb https://github.com/php-cache/mongodb-adapter
- [ ] PHPFile ?
- [x] Predis https://github.com/php-cache/predis-adapter
- [x] Redis https://github.com/php-cache/redis-adapter
- [ ] Riak ? 
- [ ] SQLite
- [x] Void https://github.com/php-cache/void-adapter
- [ ] WinCache ?
- [ ] Xcache ? 
- [ ] ZendData

**Comment by prisis** [comment]
I created a [WinCache](https://github.com/narrowspark/framework/blob/develop/src/Viserio/Cache/Adapter/WinCacheCachePool.php) and [Xcache](https://github.com/narrowspark/framework/blob/develop/src/Viserio/Cache/Adapter/XCacheCachePool.php) adapter, need to test it and update to the new tester package

**Comment by Nyholm** [comment]
Awesome!

**Comment by prisis** [comment]
I'll tell you, if its ready to copy :D

**Comment by prisis** [comment]
Add a encrypting cache adapter

**Comment by Nyholm** [comment]
I've been thinking on a encryption adapter. Have you seen this https://github.com/jeskew/psr6-encrypting-decorator? 
Is that a good package? Would you do something similar? Maybe do a merge?

**Comment by PowerKiKi** [comment]
Would the `File` adapter listed here be an implementation of [ISAM](https://en.wikipedia.org/wiki/ISAM) or similar concept ? That is a single file to store everything ?

I am working on PhpSpreadsheet (PHPExcel next version) when I stumbled upon your projects and was wondering if the `File` here could be a (future) replacement for our [DiscISAM](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/src/PhpSpreadsheet/CachedObjectStorage/DiscISAM.php) implementation...

**Comment by Nyholm** [comment]
"File" is to store all data in one file. Not sure why this is better than "file system". Is that something you want to work on?

Im closing this issue, feel free to open new issues with requests for new adapters.

**Comment by PowerKiKi** [comment]
My guess is that `File` would perform better if the data is very small but there is a lot of it. This is the case of PhpSpreadsheet where each data is the cell of a spreadsheet. I suppose it is faster to access a single file rather than create thousands of different very small files.

All that said, I don't intend to work on that in the foreseeable future. But I'm glad you would be open to the idea if that were the case later. Thanks !

**Comment by Nyholm** [comment]
You are correct. I've created an issue for that
