### ISSUE TITLE
[Chain] expiresAt incorrect if top pool did not hit

### ISSUE THREAD

**Issue by rvanlaak** [php-cache/issues#80]
We had a weird behavior with our cache chain, related to the `expiresAt` date. The chain consists of two pools, a APCu pool (`A`) on top of a filesystem pool (`B`).

So, by restarting Apache the APCu pool is empty and the filesystem fills the APCu pool again with it's existing items. This is great, it significantly lowers our load and allows us to pre-build the cache and then "put that container live".

The quite severe bug is related to the TTL on the new APCu item, that's created based on the filesystem item. Before restarting Apache the TTL is set correctly, after restarting Apache the TTL is set to none which basically means it will never expire.

@Nyholm what code in the chain does actually handle setting the TTL from `B` -> `A`?

**Comment by rvanlaak** [comment]
After some additional debugging this could also be related to the `FilesystemCachePool`. It seems that the `Chain::getItem` call [does save the item](https://github.com/php-cache/chain-adapter/blob/master/CachePoolChain.php#L98) found in pool `B` to pool `A`, but the item does not have a ttl at that specific moment. 

This would mean the `B` pool `getItem` call does not return an item with a correct `expiresAt` right? At that moment the pool is a `"Cache\CacheBundle\Cache\Recording\CachePool"`. So, at least one of the pools in the chain below `A` does not set the `expiresAt`?

**Comment by rvanlaak** [comment]
Fixed this locally, working on a PR that involves changes to `CacheItem` and `FilesystemCachePool`, `AbstractCachePool`. So far retrieving the ttl from the serialized data of the filesystem was easy, but all other adapters should also check the `expiresAt` when a new award is created.

**Comment by Nyholm** [comment]
This is solved in master
