### ISSUE TITLE
Laravel Store Cache Pool

### ISSUE THREAD

**Issue by florianv** [php-cache/issues#81]
As part of this project https://github.com/florianv/laravel-swap, I built a class to adapt a Laravel Cache Store to a PSR Cache Pool.

https://github.com/florianv/laravel-swap/blob/master/src/LaravelStoreCachePool.php

Maybe the code is not perfect but it suits my needs, but it would be more logical if it was included in PHP Cache, if you think it can be reused.

**Comment by prisis** [comment]
Im happy if you make a pr against https://github.com/php-cache/cache

**Comment by Nyholm** [comment]
Sure. I'll would also like to see that 😄

**Comment by florianv** [comment]
After all this enthusiasm, I will try to do it this week-end 😄

**Comment by prisis** [comment]
@Nyholm can we merge #82?

**Comment by aequasi** [comment]
Merged @prisis

**Comment by prisis** [comment]
can be closed :)

@Nyholm can i get rights to close tickets?

**Comment by Nyholm** [comment]
I thought you had that... Sorry.
