### ISSUE TITLE
clearOneObjectFromCache adds a new item to the store

### ISSUE THREAD

**Issue by lvanderree** [php-cache/issues#83]
Why does the function 

```php
protected function clearOneObjectFromCache($key)
{
        $this->commit();
        $this->preRemoveItem($key);
        $keyString = $this->getHierarchyKey($key, $path);
        $this->cache->incr($path);
        $this->clearHierarchyKeyCache();

        return $this->cache->del($keyString) >= 0;
}
```
https://github.com/php-cache/redis-adapter/blob/master/RedisCachePool.php#L72

call $this->cache->incr($path);
where $path is null, 
resulting in a new item:

```bash
$ Redis-cli get ""
"1"
```

When you remove items, you don't expect that new items show up, and it also costs one call extra.
Why do you want to count the numer of deletes, in an item without key?

**Comment by Nyholm** [comment]
You are correct. That is a bug. When path is null we should not call incr. 

The reason we call incr in the first place is to clear the possible hierarchy. 

Would you mind sending a PR? It would be great if you fixed other adapters as well.

**Comment by Nyholm** [comment]
Fixed by https://github.com/php-cache/cache/pull/127

**Comment by lvanderree** [comment]
Sorry I was on holiday, but thanks for fixing this issue in the meantime.

**Comment by Nyholm** [comment]
No worries. Thank you for reporting this. I think next version will be the last before 1.0
