### ISSUE TITLE
Planned Features

### ISSUE THREAD

**Issue by aequasi** [php-cache/issues#9]
This is a list of planned features: 
- [x] Logging - Log all cache transactions. 
- [x] Validation - It uses a cache from `Symfony\Component\Validator\Mapping\Cache\CacheInterface`
- [ ] Http - Instead of using disk, one maybe would like to use Redis for HttpCache
- [x] Serializer - It uses a doctrine cache
- [x] Annotation - It uses a doctrine cache
- [ ] Templating - This is just a string path to where templates should be stored
- [ ] Twig_CacheInterface

For each of these, investigate if it is a good idea to use a cache service. 

From @Nyholm:

>  I added `Twig_CacheInterface` to the list. Reference: https://www.reddit.com/r/PHP/comments/413hpc/as_an_experiment_i_wrote_two_alternative/

**Comment by prisis** [comment]
For the http cache, should we make it for psr-7 with psr-15?

**Comment by Nyholm** [comment]
I think this post referenced to replace Symfony HTTP cache with a redis cache. If you are looking for PSR-7 compatible cache I suggest the https://github.com/php-http/cache-plugin
