### ISSUE TITLE
GetItem Returns An Object

### ISSUE THREAD

**Issue by winni4eva** [php-cache/issues#91]
The documentation stops at getItem as the final method to get a stored value but I did not find that to be the case. You need to call the get method to get the stored value.

`

       
       $filesystemAdapter = new Local(__DIR__.'/');
        
        $filesystem = new Filesystem( $filesystemAdapter );

        $cache = new FilesystemCachePool( $filesystem );

       $cacheName = 'someRandomString'; 
       if( $cache->hasItem( $cacheName ) ){
            echo "Found Item In Cache";
            echo $cache->getItem( $cacheName )->get();
        }

        $item = $cache->getItem( $cacheName );
        
        $item->set( 'My Name is Winnipass....' );
        
        $item->expiresAfter( 5 );//seconds
        
        $this->cache->save( $item );

        echo "Saved New item";
        echo $this->cache->getItem( $cacheName )->get();
`

Please update the docs to save users some time...

**Comment by prisis** [comment]
Can you make a pr to https://github.com/php-cache/documentation, and add the missing info. thx!
