### ISSUE TITLE
Possible to use tags with SimpleCacheBridge?

### ISSUE THREAD

**Issue by Anahkiasen** [php-cache/issues#94]
I'm using the PSR16 interface but I'd like to use tags, is this possible in any way at the moment? I've looked at the code but I can't find any way to do that without rewriting all my code to PSR6 :/

**Comment by Nyholm** [comment]
Yes it is. It is fixed in master but not tagged yet. I'll do some work on that this weekend. 

I'll be back.

**Comment by Anahkiasen** [comment]
> but not tagged yet

oh you

**Comment by Nyholm** [comment]
Hey. I tagged new releases a couple of weeks ago. Have you tried them?

```php
$pool->set('foo', 'value'); // Simple cache
 // ..
$pool->get('foo'); // Simple cache
$item = $pool->getItem('foo');
$item->setTags(['tag_1']);
$pool->save($item);
```

**Comment by Anahkiasen** [comment]
I'm not sure I'm fully getting your code example, currently I have this:

```php
$this->cache->set('key', 'value')
```

Which I would need to change to:

```php
$item = $this->cache->getItem('key');
$item->setTags(['tag']);
$this->cache->save($item);
```

But then it's just basic PSR6, `SimpleCache` is not involved at any point no?
