### ISSUE TITLE
Fix travis issues 

### ISSUE THREAD

**Issue by prisis** [php-cache/issues#95]
https://api.travis-ci.org/jobs/209861384/log.txt?deansi=true

`PHP Warning:  Module 'memcached' already loaded in Unknown on line 0
Warning: Module 'memcached' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so' - /home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so' - /home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0
PHP Warning:  Module 'memcached' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so' - /home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0
Warning: Module 'memcached' already loaded in Unknown on line 0
Warning: PHP Startup: Unable to load dynamic library '/home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so' - /home/travis/.phpenv/versions/7.0.16/lib/php/extensions/no-debug-zts-20151012/apc.so: undefined symbol: zif_apcu_store in Unknown on line 0`

**Comment by Nyholm** [comment]
Finally fixed =)
