### ISSUE TITLE
ChainAdapter...

### ISSUE THREAD

**Issue by guyradford** [php-cache/issues#97]
Hi, 

We are seeing an interesting problem, that we are unable to repeat but have now seen twice during staging.

We are running memcached, with fileSystem cache to persist the data. We are using `$cache->save($item)` to store the cache item with an `expireAfter` value of 2 (seconds).

This appears to work for most of the times except for 2 occasions, where the same item was returned by the cache for over 12 hours... We looked at the file on disck and in memcached and I checked that the data and the timestamp is for the previous evening. 

We have been using fileSystem Cache for many months without issue, this only started to occur when we added the chain Adapter with memcached.

I have tried to repeat it and written scripts to test the cache and also been through the cachedAdspter and memcachedAdapter code looking for clues.

Any help or suggestions gratefully received.

Thank you
Guy

**Comment by Nyholm** [comment]
Thank you for reporting this. How does your chain look? Memcached first, right?

What versions are you using? In the latest versions of the adapters we have made some updates regarding this.  See https://github.com/php-cache/cache/pull/114

**Comment by guyradford** [comment]
Hi

Yes the memcached adapter is first. 

I thought we where on the latest but looking at the chain adapter it appears to be 0.4.0 not 0.5.0. 
I will go back and check all the adapters are up to date and report back if I get any further issue.

Thank you

**Comment by prisis** [comment]
@guyradford any new for this issue?

**Comment by guyradford** [comment]
We are still in the progress of moving to the latest version. Our test team, didn't want to upgrade immediately as we where to close to a launch. But it should be used in out next release. Ill keep this updated. Happy for you to close if you want.

Thank you

**Comment by prisis** [comment]
Hey @guyradford and did you find the problem?

**Comment by guyradford** [comment]
Hi, @prisis 
We haven't seen the issue since updating to the latest version. I guess this thread can now be closed.

Thank you

**Comment by prisis** [comment]
Okay :), thanks for the info!
